"use client"
import { useEffect, useRef, useState } from "react"
export default function FaceLab() {
 const [camera,setCamera]=useState(false), [message,setMessage]=useState(""), [winner,setWinner]=useState(false)
 const video=useRef<HTMLVideoElement>(null), stream=useRef<MediaStream|null>(null)
 function stop(){stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;setCamera(false)}
 useEffect(()=>()=>{stream.current?.getTracks().forEach(t=>t.stop());window.speechSynthesis?.cancel()},[])
 async function start(){ setMessage(""); try{if(!navigator.mediaDevices?.getUserMedia)throw Error("Kamera nur über HTTPS oder localhost verfügbar.");const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user"},audio:false});stream.current=s;setCamera(true);setTimeout(()=>{if(video.current){video.current.srcObject=s;video.current.play().catch(()=>{})}},0)}catch(e){setMessage(e instanceof Error?e.message:"Kamera nicht verfügbar")}}
 function speak(text:string){if(!("speechSynthesis" in window)){setMessage("Sprachausgabe nicht verfügbar.");return}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="de-DE";u.rate=0.93;window.speechSynthesis.speak(u)}
 return <main className="min-h-screen bg-[#060910] text-white px-4 py-10"><div className="mx-auto max-w-3xl">
 <div className="text-xs font-black uppercase tracking-[.3em] text-orange-400">EMD · Testlabor</div><h1 className="mt-2 text-3xl font-black">FACE ID · TEST</h1><p className="mt-3 text-sm text-slate-400">Unverlinkte Testseite. Keine Turnierergebnisse werden geändert.</p>
 <div className="mt-8 grid gap-6">
<div className="rounded-2xl border border-orange-500/30 bg-[#101722] p-5"><h2 className="text-xl font-bold">1 · Kamera testen</h2><p className="mt-2 text-sm text-slate-400">Nur lokale Vorschau. Kein Upload, keine Aufnahme und noch kein Gesichtsabgleich.</p><div className="mt-4 overflow-hidden rounded-xl bg-black aspect-video flex items-center justify-center">{camera?<video ref={video} autoPlay muted playsInline className="w-full h-full object-cover scale-x-[-1]"/>:<span className="text-slate-500">Kamera ausgeschaltet</span>}</div><button onClick={camera?stop:start} className="mt-4 rounded-xl bg-orange-600 px-5 py-3 font-bold">{camera?"Kamera ausschalten":"Frontkamera starten"}</button>{message&&<p className="mt-3 text-sm text-amber-300">{message}</p>}</div>
 <div className="rounded-2xl border border-white/10 bg-[#101722] p-5"><h2 className="text-xl font-bold">2 · Begrüßung testen</h2><p className="mt-2 text-sm text-slate-400">Jimmy ist für diese Demo fest eingestellt – die Kamera identifiziert dich noch nicht.</p><button onClick={()=>speak("Servus Jimmy! Na, schon wieder gewonnen? Willkommen beim EMD Autopilot!")} className="mt-4 rounded-xl bg-orange-600 px-5 py-3 font-bold">Begrüßung abspielen 🔊</button></div>
 <div className="rounded-2xl border border-white/10 bg-[#101722] p-5"><h2 className="text-xl font-bold">3 · Ergebnis-Demo</h2><p className="mt-2 text-slate-300">Testspiel · Jimmy gegen Manfred · 3 : 1</p><button onClick={()=>{setWinner(true);speak("Gratuliere Jimmy! Drei zu eins gewonnen. Deine nächste Partie wird vorbereitet!")}} className="mt-4 rounded-xl bg-orange-600 px-5 py-3 font-bold">Testsieg simulieren</button>{winner&&<p className="mt-4 text-green-300 font-bold">Test erfolgreich – keine Daten gespeichert.</p>}</div>
 </div></div></main>
}
