"use client"
import { useEffect, useRef, useState } from "react"
export default function FaceLab({access, enabled}:{access:boolean,enabled:boolean}) {
 const [allowed,setAllowed]=useState(access), [pass,setPass]=useState(""),[error,setError]=useState(""), [busy,setBusy]=useState(false)
 const [camera,setCamera]=useState(false), [message,setMessage]=useState(""), [winner,setWinner]=useState(false)
 const video=useRef<HTMLVideoElement>(null), stream=useRef<MediaStream|null>(null)
 function stop(){stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;setCamera(false)}
 useEffect(()=>()=>{stream.current?.getTracks().forEach(t=>t.stop());window.speechSynthesis?.cancel()},[])
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError(""); try{const r=await fetch("/api/face-id-labor/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:pass})});const j=await r.json(); if(!r.ok)throw Error(j.error||"Zugriff verweigert");setAllowed(true);setPass("")}catch(e){setError(e instanceof Error?e.message:"Fehler")}finally{setBusy(false)}}
 async function start(){ setMessage(""); try{if(!navigator.mediaDevices?.getUserMedia)throw Error("Kamera nur über HTTPS oder localhost verfügbar.");const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user"},audio:false});stream.current=s;setCamera(true);setTimeout(()=>{if(video.current){video.current.srcObject=s;video.current.play().catch(()=>{})}},0)}catch(e){setMessage(e instanceof Error?e.message:"Kamera nicht verfügbar")}}
 function speak(text:string){if(!("speechSynthesis" in window)){setMessage("Sprachausgabe nicht verfügbar.");return}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="de-DE";u.rate=0.93;window.speechSynthesis.speak(u)}
 async function logout(){stop();await fetch("/api/face-id-labor/logout",{method:"POST"});setAllowed(false);setWinner(false)}
 return <main className="min-h-screen bg-[#060910] text-white px-4 py-10"><div className="mx-auto max-w-3xl">
 <div className="text-xs font-black uppercase tracking-[.3em] text-orange-400">EMD · Internes Labor</div><h1 className="mt-2 text-3xl font-black">FACE ID · TEST</h1><p className="mt-3 text-sm text-slate-400">Versteckte Testseite. Keine Turnierergebnisse werden geändert.</p>
 {!enabled?<div className="mt-8 rounded-2xl border border-amber-500/40 p-6">Der Testbereich ist gesperrt. Bitte EMD_FACE_LAB_PASSWORD (mindestens 12 Zeichen) und EMD_FACE_LAB_SECRET (mindestens 16 Zeichen) auf dem Server setzen.</div>:!allowed?<form onSubmit={login} className="mt-8 rounded-2xl border border-white/10 bg-white/5 p-6 space-y-4"><label className="block text-sm font-bold" htmlFor="face-password">Privates Testpasswort</label><input id="face-password" type="password" autoComplete="off" className="w-full rounded-xl bg-black border border-white/20 p-4 text-white" value={pass} onChange={e=>setPass(e.target.value)} required/><button disabled={busy} className="rounded-xl bg-orange-600 px-6 py-3 font-bold">Labor öffnen</button>{error&&<p className="text-red-300">{error}</p>}</form>:<div className="mt-8 grid gap-6">
 <div className="rounded-2xl border border-orange-500/30 bg-[#101722] p-5"><h2 className="text-xl font-bold">1 · Kamera testen</h2><p className="mt-2 text-sm text-slate-400">Nur lokale Vorschau. Kein Upload, keine Aufnahme und noch kein Gesichtsabgleich.</p><div className="mt-4 overflow-hidden rounded-xl bg-black aspect-video flex items-center justify-center">{camera?<video ref={video} autoPlay muted playsInline className="w-full h-full object-cover scale-x-[-1]"/>:<span className="text-slate-500">Kamera ausgeschaltet</span>}</div><button onClick={camera?stop:start} className="mt-4 rounded-xl bg-orange-600 px-5 py-3 font-bold">{camera?"Kamera ausschalten":"Frontkamera starten"}</button>{message&&<p className="mt-3 text-sm text-amber-300">{message}</p>}</div>
 <div className="rounded-2xl border border-white/10 bg-[#101722] p-5"><h2 className="text-xl font-bold">2 · Begrüßung testen</h2><p className="mt-2 text-sm text-slate-400">Jimmy ist für diese Demo fest eingestellt – die Kamera identifiziert dich noch nicht.</p><button onClick={()=>speak("Servus Jimmy! Na, schon wieder gewonnen? Willkommen beim EMD Autopilot!")} className="mt-4 rounded-xl bg-orange-600 px-5 py-3 font-bold">Begrüßung abspielen 🔊</button></div>
 <div className="rounded-2xl border border-white/10 bg-[#101722] p-5"><h2 className="text-xl font-bold">3 · Ergebnis-Demo</h2><p className="mt-2 text-slate-300">Testspiel · Jimmy gegen Manfred · 3 : 1</p><button onClick={()=>{setWinner(true);speak("Gratuliere Jimmy! Drei zu eins gewonnen. Deine nächste Partie wird vorbereitet!")}} className="mt-4 rounded-xl bg-orange-600 px-5 py-3 font-bold">Testsieg simulieren</button>{winner&&<p className="mt-4 text-green-300 font-bold">Test erfolgreich – keine Daten gespeichert.</p>}</div>
 <button onClick={logout} className="rounded-xl border border-white/20 py-3">Testlabor sperren</button></div>}</div></main>
}
