import { NextResponse } from "next/server"
import { createClient } from "@supabase/supabase-js"

function client(){return createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!,{auth:{persistSession:false,autoRefreshToken:false}})}
async function adminFrom(request:Request){const auth=request.headers.get("authorization")||"";const token=auth.toLowerCase().startsWith("bearer ")?auth.slice(7).trim():"";if(!token)return null;const s=client();const {data:u}=await s.auth.getUser(token);if(!u.user)return null;const {data:p}=await s.from("user_profiles").select("is_admin").eq("user_id",u.user.id).maybeSingle();return p?.is_admin?u.user:null}

export async function GET(request:Request){if(!await adminFrom(request))return NextResponse.json({error:"Nicht erlaubt."},{status:403});const s=client();const {data:events,error}=await s.from("dach_events").select("id,name,start_date,event_date,event_time,location,city,max_participants,registration_enabled,registration_mode,show_participants,event_status").eq("registration_mode","public_form").order("start_date",{ascending:true});if(error)return NextResponse.json({error:error.message},{status:500});const {data:regs}=await s.from("public_event_registrations").select("id,event_id,full_name,player_name,email,phone,status,registered_at,cancelled_at").order("registered_at",{ascending:false});return NextResponse.json({events:events||[],registrations:regs||[]})}

export async function PATCH(request:Request){if(!await adminFrom(request))return NextResponse.json({error:"Nicht erlaubt."},{status:403});const b=await request.json().catch(()=>null);const s=client();if(b?.type==="event"){const patch:any={};if(typeof b.registration_enabled==="boolean")patch.registration_enabled=b.registration_enabled;if(typeof b.show_participants==="boolean")patch.show_participants=b.show_participants;const {error}=await s.from("dach_events").update(patch).eq("id",b.id);if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({ok:true})}if(b?.type==="registration"){const status=b.status==="active"?"active":"cancelled";const {error}=await s.from("public_event_registrations").update({status,cancelled_at:status==="cancelled"?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq("id",b.id);if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({ok:true})}return NextResponse.json({error:"Ungültige Aktion."},{status:400})}
